# Generated by Django 6.0.1 on 2026-02-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default='0000000000', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pregunta_seguridad',
            field=models.CharField(choices=[('mascota', '¿Cómo se llama tu primera mascota?'), ('madre', '¿Cuál es el segundo nombre de tu madre?'), ('ciudad', '¿En qué ciudad naciste?')], max_length=50),
        ),
    ]
