# Generated by Django 5.2.10 on 2026-03-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rolpago'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='decimo_cuarto_sueldo_modalidad',
            field=models.CharField(choices=[('anual', 'Anual'), ('mensual', 'Mensual')], default='anual', max_length=10),
        ),
        migrations.AddField(
            model_name='empleado',
            name='decimo_tercer_sueldo_modalidad',
            field=models.CharField(choices=[('anual', 'Anual'), ('mensual', 'Mensual')], default='anual', max_length=10),
        ),
    ]
