# Generated by Django 5.2.10 on 2026-03-24 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_empleado_decimo_cuarto_sueldo_modalidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=17, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=13)),
                ('direccion', models.CharField(max_length=255)),
                ('establecimiento', models.CharField(default='001', max_length=3)),
                ('punto_emision', models.CharField(default='001', max_length=3)),
                ('secuencial', models.CharField(max_length=9)),
                ('cliente_nombre', models.CharField(max_length=255)),
                ('cliente_identificacion', models.CharField(max_length=13)),
                ('tipo_identificacion', models.CharField(choices=[('04', 'RUC'), ('05', 'Cédula'), ('06', 'Pasaporte'), ('07', 'Consumidor final')], default='05', max_length=2)),
                ('cliente_direccion', models.CharField(max_length=255)),
                ('subtotal_0', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal_12', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('forma_pago', models.CharField(max_length=100)),
                ('tiempo_pago', models.CharField(blank=True, max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('clave_acceso', models.CharField(max_length=49)),
                ('numero_autorizacion', models.CharField(blank=True, max_length=49)),
                ('fecha_emision', models.DateField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sin_impuestos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.factura')),
            ],
        ),
    ]
